### ISSUE TITLE
help plis url print

### ISSUE THREAD

**Issue by xoceunder** [chtaylo2/Roku-TaylorMovies#2]
help plis url print

  'Make a request for each "row" in the UI (in the order that you want content filled)
  URLs = [
    "https://XXXXXXXXXXX/roku/roku-movies/display.pl?start=0&end=6&uuid=" + device.GetDeviceUniqueId(),
    "https://XXXXXXXXXXX/roku/roku-movies/display.pl?start=1&end=6&uuid=" + device.GetDeviceUniqueId(),
    "https://XXXXXXXXXXX/roku/roku-movies/display.pl?start=2&end=6&uuid=" + device.GetDeviceUniqueId(),
    "https://XXXXXXXXXXX/roku/roku-movies/display.pl?start=3&end=6&uuid=" + device.GetDeviceUniqueId(),
    "https://XXXXXXXXXXX/roku/roku-movies/display.pl?start=4&end=6&uuid=" + device.GetDeviceUniqueId(),
    "https://XXXXXXXXXXX/roku/roku-movies/display.pl?start=5&end=6&uuid=" + device.GetDeviceUniqueId()
  ]

**Comment by chtaylo2** [comment]
Sorry,  as documentation says "Private channel for home use."

**Comment by xoceunder** [comment]
And what are the documents to use them I would like

**Comment by xoceunder** [comment]
Could you help me to be able to do this of the photo I want to upload the individual category

https://image.prntscr.com/image/-Xt4CljcRF27nRKFXfZ5ng.png
